[project]
name = "antithesis-sdk"
version = "0.1.0"
description = "Antithesis SDK for Python"
dependencies = [
    # "whatever",
]

[build-system]
requires = ["setuptools>=61.0", "wheel", "Cython"]
build-backend = "setuptools.build_meta"

[project.scripts]
# always "message text" t t f t f 
always = "assertions:cmd_always"

# sometimes "message text" t t f t f 
sometimes = "assertions:cmd_sometimes"

# addx 10 17
addx = "assertions:add"

# subx 100 31
subx = "assertions:sub"

# [tool.pydeploy]
# exclude_libs = []

